package com.cloudflow.audit.domain;

/** Audited actions. Names are stable identifiers used in filters and exports. */
public enum AuditAction {
  // Authentication
  USER_SIGNED_IN,
  USER_SIGNED_OUT,
  REFRESH_TOKEN_REUSE_DETECTED,
  // Organizations and members
  ORGANIZATION_CREATED,
  ORGANIZATION_UPDATED,
  ORGANIZATION_DELETED,
  MEMBER_ADDED,
  MEMBER_ROLE_CHANGED,
  MEMBER_REMOVED,
  // Projects and configuration
  PROJECT_CREATED,
  PROJECT_UPDATED,
  PROJECT_DELETED,
  ENVIRONMENT_CREATED,
  ENVIRONMENT_UPDATED,
  ENVIRONMENT_DELETED,
  VARIABLE_SET,
  VARIABLE_DELETED,
  DEPLOYMENT_CONFIG_UPDATED,
  // Deployments and CI/CD
  DEPLOYMENT_TRIGGERED,
  DEPLOYMENT_ROLLBACK_TRIGGERED,
  DEPLOYMENT_CANCELLED,
  PIPELINE_COMMITTED,
  PIPELINE_DELETED,
  DEPLOY_TOKEN_CREATED,
  DEPLOY_TOKEN_REVOKED,
  // AI
  AI_SUGGESTION_APPLIED,
  AI_SUGGESTION_REJECTED
}
