package com.cloudflow.cicd.service;

import com.cloudflow.environment.domain.ConfigTemplate;
import com.cloudflow.environment.domain.DeploymentSettings;
import com.cloudflow.environment.domain.EnvironmentType;
import com.cloudflow.project.domain.AppType;
import java.util.Locale;
import java.util.stream.Collectors;
import org.springframework.stereotype.Component;

/**
 * Generates the standard CloudFlow GitHub Actions workflow for one environment:
 *
 * <pre>test → build → docker (build + push to GHCR) → deploy (CloudFlow) → health-check</pre>
 *
 * The deploy job asks CloudFlow to deploy the exact commit; the health-check job waits until
 * CloudFlow reports the deployment healthy, so a failed rollout fails the workflow.
 */
@Component
public class WorkflowGenerator {

  static final String DEPLOY_TOKEN_HEADER = "X-CloudFlow-Deploy-Token";
  static final String GENERATED_DOCKERFILE = ".cloudflow.Dockerfile";
  private static final String CHECKOUT = "actions/checkout@v7";

  /**
   * @param generatedDockerfile the Dockerfile CloudFlow generates for template-based builds, or
   *     {@code null} for the Docker template (the repository's own Dockerfile is used)
   */
  public record WorkflowSpec(
      String projectName,
      EnvironmentType environment,
      String branch,
      DeploymentSettings settings,
      AppType appType,
      String generatedDockerfile) {}

  public static String workflowPath(EnvironmentType environment) {
    return ".github/workflows/cloudflow-" + environment.name().toLowerCase(Locale.ROOT) + ".yml";
  }

  public static String deployTokenSecretName(EnvironmentType environment) {
    return "CLOUDFLOW_DEPLOY_TOKEN_" + environment.name();
  }

  public String generate(WorkflowSpec spec) {
    String environmentName = spec.environment().name().toLowerCase(Locale.ROOT);
    String title = spec.environment().name().charAt(0) + environmentName.substring(1);
    StringBuilder yaml = new StringBuilder();
    yaml.append(
        """
        # Generated by CloudFlow for %s (%s).
        # CloudFlow overwrites this file when the pipeline is regenerated.
        # Required repository secrets: CLOUDFLOW_URL, %s
        name: CloudFlow · %s

        on:
          push:
            branches: [%s]
          workflow_dispatch:

        permissions:
          contents: read
          packages: write

        concurrency:
          group: cloudflow-%s
          cancel-in-progress: false

        jobs:
        """
            .formatted(
                singleLine(spec.projectName()),
                title,
                deployTokenSecretName(spec.environment()),
                title,
                yamlString(spec.branch()),
                environmentName));
    yaml.append(testJob(spec));
    yaml.append(buildJob(spec));
    yaml.append(dockerJob(spec, environmentName));
    yaml.append(deployJob(spec));
    yaml.append(healthCheckJob(spec));
    return yaml.toString();
  }

  private String testJob(WorkflowSpec spec) {
    return """
          test:
            name: Test
            runs-on: ubuntu-latest
            steps:
              - uses: %s
        %s      - name: Run tests
                run: |
        %s
        """
        .formatted(CHECKOUT, setupSteps(spec), indent(testScript(spec), 10));
  }

  private String buildJob(WorkflowSpec spec) {
    return """
          build:
            name: Build
            needs: test
            runs-on: ubuntu-latest
            steps:
              - uses: %s
        %s      - name: Build
                run: |
        %s
        """
        .formatted(CHECKOUT, setupSteps(spec), indent(buildScript(spec), 10));
  }

  private String dockerJob(WorkflowSpec spec, String environmentName) {
    String dockerfile =
        spec.generatedDockerfile() == null
            ? spec.settings().dockerfilePath()
            : GENERATED_DOCKERFILE;
    String writeDockerfile =
        spec.generatedDockerfile() == null
            ? ""
            : """
                    - name: Write the CloudFlow-generated Dockerfile
                      run: |
                        cat > %s <<'CLOUDFLOW_DOCKERFILE'
              %s
                        CLOUDFLOW_DOCKERFILE
              """
                .formatted(
                    GENERATED_DOCKERFILE,
                    indent(escapeExpressions(spec.generatedDockerfile().stripTrailing()), 10));
    return """
          docker:
            name: Docker build and push
            needs: build
            runs-on: ubuntu-latest
            steps:
              - uses: %s
        %s      - name: Image name
                run: echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"
              - uses: docker/login-action@v4
                with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
              - uses: docker/build-push-action@v7
                with:
                  context: .
                  file: %s
                  push: true
                  tags: |
                    ${{ env.IMAGE }}:${{ github.sha }}
                    ${{ env.IMAGE }}:%s
        """
        .formatted(CHECKOUT, writeDockerfile, yamlString(dockerfile), environmentName);
  }

  private String deployJob(WorkflowSpec spec) {
    return """
          deploy:
            name: Deploy with CloudFlow
            needs: docker
            runs-on: ubuntu-latest
            outputs:
              deployment-id: ${{ steps.deploy.outputs.deployment-id }}
            steps:
              - name: Trigger CloudFlow deployment
                id: deploy
                env:
                  CLOUDFLOW_URL: ${{ secrets.CLOUDFLOW_URL }}
                  CLOUDFLOW_DEPLOY_TOKEN: ${{ secrets.%s }}
                run: |
                  response=$(curl --fail-with-body -sS -X POST "$CLOUDFLOW_URL/api/v1/pipeline-hooks/deploy" \\
                    -H "%s: $CLOUDFLOW_DEPLOY_TOKEN" \\
                    -H "Content-Type: application/json" \\
                    -d "{\\"commitSha\\":\\"$GITHUB_SHA\\",\\"runId\\":$GITHUB_RUN_ID}")
                  echo "$response"
                  echo "deployment-id=$(echo "$response" | jq -r .id)" >> "$GITHUB_OUTPUT"
        """
        .formatted(deployTokenSecretName(spec.environment()), DEPLOY_TOKEN_HEADER);
  }

  private String healthCheckJob(WorkflowSpec spec) {
    return """
          health-check:
            name: Health check
            needs: deploy
            runs-on: ubuntu-latest
            timeout-minutes: 25
            steps:
              - name: Wait until CloudFlow reports the deployment healthy
                env:
                  CLOUDFLOW_URL: ${{ secrets.CLOUDFLOW_URL }}
                  CLOUDFLOW_DEPLOY_TOKEN: ${{ secrets.%s }}
                  DEPLOYMENT_ID: ${{ needs.deploy.outputs.deployment-id }}
                run: |
                  for _ in $(seq 1 120); do
                    response=$(curl --fail-with-body -sS "$CLOUDFLOW_URL/api/v1/pipeline-hooks/deployments/$DEPLOYMENT_ID" \\
                      -H "%s: $CLOUDFLOW_DEPLOY_TOKEN")
                    status=$(echo "$response" | jq -r .status)
                    echo "Deployment status: $status"
                    case "$status" in
                      SUCCEEDED) echo "Live at $(echo "$response" | jq -r '.url // "n/a"')"; exit 0 ;;
                      FAILED|CANCELLED) echo "::error::$(echo "$response" | jq -r .failureReason)"; exit 1 ;;
                    esac
                    sleep 10
                  done
                  echo "::error::Timed out waiting for the deployment"
                  exit 1
        """
        .formatted(deployTokenSecretName(spec.environment()), DEPLOY_TOKEN_HEADER);
  }

  /** Language toolchain steps, indented as list items of {@code steps:}. */
  private String setupSteps(WorkflowSpec spec) {
    String version = spec.settings().runtimeVersion();
    return switch (spec.settings().template()) {
      case JAVA ->
          """
                - uses: actions/setup-java@v6
                  with:
                    distribution: temurin
                    java-version: "%s"
          """
                  .formatted(version)
              + (spec.appType() == AppType.JAVA_GRADLE
                  ? "      - uses: gradle/actions/setup-gradle@v6\n"
                  : "");
      case NODE ->
          """
                - uses: actions/setup-node@v7
                  with:
                    node-version: "%s"
          """
              .formatted(version);
      case PYTHON ->
          """
                - uses: actions/setup-python@v7
                  with:
                    python-version: "%s"
          """
              .formatted(version);
      case DOCKER -> "";
    };
  }

  private String testScript(WorkflowSpec spec) {
    return switch (spec.settings().template()) {
      case JAVA ->
          spec.appType() == AppType.JAVA_GRADLE
              ? "if [ -f gradlew ]; then ./gradlew test; else gradle test; fi"
              : "mvn -B test";
      case NODE -> "npm ci\nnpm test --if-present";
      case PYTHON ->
          """
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if ls test_*.py tests >/dev/null 2>&1; then
            pip install pytest
            pytest
          else
            echo "No tests found"
          fi""";
      case DOCKER ->
          // The Docker template does not know the language; detect common test runners.
          """
          if [ -f package.json ]; then npm ci && npm test --if-present
          elif [ -f pom.xml ]; then mvn -B test
          elif [ -f gradlew ]; then ./gradlew test
          elif [ -f requirements.txt ]; then pip install -r requirements.txt && (pytest || [ $? -eq 5 ])
          else echo "No test runner detected; tests run inside the Docker build if defined there"
          fi""";
    };
  }

  private String buildScript(WorkflowSpec spec) {
    if (spec.settings().template() == ConfigTemplate.DOCKER) {
      return "docker build --file " + shellQuote(spec.settings().dockerfilePath()) + " .";
    }
    String command = spec.settings().buildCommand();
    if (command == null || command.isBlank()) {
      return "echo \"No build command configured\"";
    }
    return escapeExpressions(command);
  }

  /** Prevents GitHub from evaluating {@code ${{ }}} expressions inside user-provided text. */
  static String escapeExpressions(String text) {
    return text.replace("${{", "${{ '${{' }}");
  }

  static String yamlString(String value) {
    return "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
  }

  private static String shellQuote(String value) {
    return "'" + value.replace("'", "'\\''") + "'";
  }

  private static String singleLine(String value) {
    return value.replace('\n', ' ').replace('\r', ' ');
  }

  private static String indent(String text, int spaces) {
    String prefix = " ".repeat(spaces);
    return text.lines()
        .map(line -> line.isEmpty() ? line : prefix + line)
        .collect(Collectors.joining("\n"));
  }
}
