package com.cloudflow.deployment.engine;

import com.cloudflow.environment.domain.ConfigTemplate;
import com.cloudflow.environment.domain.DeploymentSettings;
import com.cloudflow.project.domain.AppType;
import org.springframework.stereotype.Component;

/**
 * Generates Dockerfiles for the Java, Node.js, and Python templates. Generated images run as a
 * non-root user and prepare {@code /data} for the environment's persistent volume.
 *
 * <p>Commands come from the deployment configuration and have already been validated to be single
 * lines. Start commands are JSON-escaped into the exec form of {@code CMD}.
 */
@Component
public class DockerfileGenerator {

  public static final String DATA_DIRECTORY = "/data";

  public String generate(DeploymentSettings settings, AppType appType) {
    return switch (settings.template()) {
      case JAVA -> java(settings, appType);
      case NODE -> node(settings);
      case PYTHON -> python(settings);
      case DOCKER ->
          throw new IllegalArgumentException(
              "The " + ConfigTemplate.DOCKER + " template uses the repository's Dockerfile");
    };
  }

  private static String java(DeploymentSettings settings, AppType appType) {
    boolean gradle = appType == AppType.JAVA_GRADLE;
    String builderImage =
        gradle
            ? "gradle:jdk" + settings.runtimeVersion()
            : "maven:3.9-eclipse-temurin-" + settings.runtimeVersion();
    String jarDirectory = gradle ? "build/libs" : "target";
    return """
        # Generated by CloudFlow (Java template)
        FROM %s AS build
        WORKDIR /src
        COPY . .
        RUN %s
        # Pick the runnable jar, skipping Gradle's plain jar and Maven's original jar.
        RUN mkdir -p /out && cp "$(ls %s/*.jar | grep -v -e '-plain.jar$' -e '.original$' | head -n 1)" /out/app.jar

        FROM eclipse-temurin:%s-jre
        WORKDIR /app
        RUN groupadd --system app && useradd --system --gid app --home-dir /app app \\
            && mkdir -p %s && chown app:app %s
        COPY --from=build /out/app.jar app.jar
        USER app
        EXPOSE %d
        CMD ["sh", "-c", %s]
        """
        .formatted(
            builderImage,
            settings.buildCommand(),
            jarDirectory,
            settings.runtimeVersion(),
            DATA_DIRECTORY,
            DATA_DIRECTORY,
            settings.containerPort(),
            jsonString(settings.startCommand()));
  }

  private static String node(DeploymentSettings settings) {
    String build = settings.buildCommand() == null ? "npm ci" : settings.buildCommand();
    return """
        # Generated by CloudFlow (Node.js template)
        FROM node:%s-alpine
        WORKDIR /app
        COPY . .
        RUN %s
        RUN mkdir -p %s && chown node:node %s
        ENV NODE_ENV=production
        USER node
        EXPOSE %d
        CMD ["sh", "-c", %s]
        """
        .formatted(
            settings.runtimeVersion(),
            build,
            DATA_DIRECTORY,
            DATA_DIRECTORY,
            settings.containerPort(),
            jsonString(settings.startCommand()));
  }

  private static String python(DeploymentSettings settings) {
    String build =
        settings.buildCommand() == null
            ? "if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi"
            : settings.buildCommand();
    return """
        # Generated by CloudFlow (Python template)
        FROM python:%s-slim
        ENV PYTHONUNBUFFERED=1 PIP_DISABLE_PIP_VERSION_CHECK=1
        WORKDIR /app
        COPY . .
        RUN %s
        RUN groupadd --system app && useradd --system --gid app --home-dir /app app \\
            && mkdir -p %s && chown app:app %s
        USER app
        EXPOSE %d
        CMD ["sh", "-c", %s]
        """
        .formatted(
            settings.runtimeVersion(),
            build,
            DATA_DIRECTORY,
            DATA_DIRECTORY,
            settings.containerPort(),
            jsonString(settings.startCommand()));
  }

  /** Encodes a value as a JSON string literal for exec-form Dockerfile instructions. */
  static String jsonString(String value) {
    StringBuilder json = new StringBuilder("\"");
    for (char c : value.toCharArray()) {
      switch (c) {
        case '"' -> json.append("\\\"");
        case '\\' -> json.append("\\\\");
        case '\t' -> json.append("\\t");
        default -> {
          if (c < 0x20) {
            json.append(String.format("\\u%04x", (int) c));
          } else {
            json.append(c);
          }
        }
      }
    }
    return json.append('"').toString();
  }
}
