package com.cloudflow.monitoring.domain;

public enum EventType {
  DEPLOYMENT_STARTED,
  DEPLOYMENT_SUCCEEDED,
  DEPLOYMENT_FAILED,
  DEPLOYMENT_CANCELLED,
  DEPLOYMENT_ROLLED_BACK,
  HEALTH_DEGRADED,
  HEALTH_RECOVERED,
  CONTAINER_RESTARTED,
  CONTAINER_STOPPED
}
